const fs = require('fs');

const scraped = JSON.parse(fs.readFileSync('data/live_scraped_ghalati.json', 'utf8'));
const perfumes = JSON.parse(fs.readFileSync('public/data/perfumes.json', 'utf8'));

// Note translation dictionary
const DICT = [
  [/فراولة/g, 'Strawberry'],
  [/تفاح/g, 'Apple'],
  [/قرفة/g, 'Cinnamon'],
  [/ريحان/g, 'Basil'],
  [/برتقال/g, 'Orange'],
  [/برغموت/g, 'Bergamot'],
  [/زنبق الوادي/g, 'Lily of the Valley'],
  [/يلانغ يلانغ|يلانج يلانج/g, 'Ylang-Ylang'],
  [/ورد تركي/g, 'Turkish Rose'],
  [/ورد قرطاجي/g, 'Carthaginian Rose'],
  [/ورد طائفي/g, 'Taif Rose'],
  [/ورد فواح/g, 'Fragrant Rose'],
  [/ورد/g, 'Rose'],
  [/قهوة/g, 'Coffee'],
  [/ياسمين راقي/g, 'Noble Jasmine'],
  [/ياسمين/g, 'Jasmine'],
  [/عنبر دافئ/g, 'Warm Amber'],
  [/عنبر جاف/g, 'Dry Amber'],
  [/عنبر/g, 'Amber'],
  [/خشب الصندل الأسترالي/g, 'Australian Sandalwood'],
  [/خشب الصندل/g, 'Sandalwood'],
  [/صندل كريمي/g, 'Creamy Sandalwood'],
  [/صندل/g, 'Sandalwood'],
  [/فانيليا مدغشقر/g, 'Madagascar Vanilla'],
  [/فانيليا/g, 'Vanilla'],
  [/فانيلا/g, 'Vanilla'],
  [/خشب الأرز الدافئ/g, 'Warm Cedarwood'],
  [/خشب الأرز/g, 'Cedarwood'],
  [/خشب الارز/g, 'Cedarwood'],
  [/أرز/g, 'Cedarwood'],
  [/مسك ملكي/g, 'Royal Musk'],
  [/مسك راقي/g, 'Prestige Musk'],
  [/مسك دافئ/g, 'Warm Musk'],
  [/مسك/g, 'Musk'],
  [/تونكا/g, 'Tonka Bean'],
  [/فول التونكا/g, 'Tonka Bean'],
  [/جريب فروت|قريب فروت/g, 'Grapefruit'],
  [/باتشولي/g, 'Patchouli'],
  [/عود وزعفران/g, 'Oud & Saffron'],
  [/عود فاخر/g, 'Royal Oud'],
  [/خشب العود/g, 'Agarwood / Oud'],
  [/عود/g, 'Oud'],
  [/زعفران إسباني/g, 'Spanish Saffron'],
  [/زعفران فاخر/g, 'Precious Saffron'],
  [/زعفران/g, 'Saffron'],
  [/فلفل أسود/g, 'Black Pepper'],
  [/فلفل وردي/g, 'Pink Pepper'],
  [/فلفل حلو/g, 'Sweet Pimento'],
  [/ليمون/g, 'Lemon'],
  [/مكونات محمصة/g, 'Roasted Accords'],
  [/إبرة الراعي/g, 'Geranium'],
  [/خشب الغاياك/g, 'Guaiac Wood'],
  [/بنفسج/g, 'Violet'],
  [/أوراق البنفسج/g, 'Violet Leaves'],
  [/أوراق البنفسج المصري/g, 'Egyptian Violet Leaves'],
  [/جلد أبيض/g, 'White Leather'],
  [/جلود/g, 'Leather'],
  [/جلد/g, 'Leather'],
  [/نجيل الهند/g, 'Vetiver'],
  [/فتيفر/g, 'Vetiver'],
  [/زبدة السوسن/g, 'Iris Butter'],
  [/زبدة جذور السوسن/g, 'Orris Root Butter'],
  [/سوسن/g, 'Iris'],
  [/كراميل/g, 'Caramel'],
  [/خشب الكشمير/g, 'Cashmere Wood'],
  [/كشميران/g, 'Cashmeran'],
  [/خوخ ناضج/g, 'Ripe Peach'],
  [/خوخ/g, 'Peach'],
  [/توت العليق/g, 'Raspberry'],
  [/توت/g, 'Berries'],
  [/توتيات حمراء/g, 'Red Berries'],
  [/توت أحمر/g, 'Red Berries'],
  [/توت مثلج/g, 'Iced Berries'],
  [/بخور/g, 'Incense'],
  [/شوكولاتة/g, 'Chocolate'],
  [/غزل البنات/g, 'Cotton Candy'],
  [/زهرة تيارا/g, 'Tiare Flower'],
  [/فواكه استوائية/g, 'Tropical Fruits'],
  [/فواكه مثلجة/g, 'Iced Fruits'],
  [/فواكه حمراء/g, 'Red Fruits'],
  [/فواكه/g, 'Fruits'],
  [/أناناس/g, 'Pineapple'],
  [/زهور بيضاء/g, 'White Flowers'],
  [/زهر البرتقال/g, 'Orange Blossom'],
  [/زهرة البرتقال/g, 'Orange Blossom'],
  [/أخشاب/g, 'Precious Woods'],
  [/أخشاب الكشمير/g, 'Cashmere Woods'],
  [/ماندرين/g, 'Mandarin'],
  [/قرنفل/g, 'Clove'],
  [/غردينيا/g, 'Gardenia'],
  [/قاردينيا/g, 'Gardenia'],
  [/فريق البحث والتطوير بغلاتي/g, 'Ghalati R&D Perfumers'],
  [/أدرينالين/g, 'Adrenaline Accord'],
  [/صنوبر/g, 'Pine'],
  [/كشمش أسود/g, 'Blackcurrant'],
  [/بخور مريم/g, 'Cyclamen'],
  [/نرجس/g, 'Narcissus'],
  [/بنزوين/g, 'Benzoin'],
  [/جاوي/g, 'Benzoin'],
  [/لبان جاوي/g, 'Benzoin'],
  [/مسك الروم/g, 'Tuberose'],
  [/قشر الزنجبيل/g, 'Ginger Zest'],
  [/زنجبيل/g, 'Ginger'],
  [/امبروكسان/g, 'Ambroxan'],
  [/يوسفي/g, 'Tangerine'],
  [/أوسمانثوس/g, 'Osmanthus'],
  [/أمورتال/g, 'Immortelle'],
  [/الامبريت المكثف/g, 'Intense Ambrette'],
  [/امبريت/g, 'Ambrette'],
  [/ميموزا/g, 'Mimosa'],
  [/لابندوم الاسباني|لابدانوم/g, 'Spanish Labdanum'],
  [/إكليل الجبل/g, 'Rosemary'],
  [/توليفة بحرية نظيفة/g, 'Clean Marine Breeze'],
  [/روائح بحرية/g, 'Marine Notes'],
  [/مائي/g, 'Aquatic Notes'],
  [/عشبي/g, 'Herbal Notes'],
  [/راوند/g, 'Rhubarb'],
  [/فريزيا/g, 'Freesia'],
  [/ألدهيد/g, 'Aldehydes'],
  [/كمثرى/g, 'Pear'],
  [/جوز الهند/g, 'Coconut'],
  [/عرعر/g, 'Juniper'],
  [/طحلب السنديان/g, 'Oakmoss'],
  [/فاكهة الباشن/g, 'Passion Fruit'],
  [/كركم/g, 'Turmeric'],
  [/مارشميلو/g, 'Marshmallow'],
  [/مارشملو/g, 'Marshmallow'],
  [/كوكتيل شمبانيا/g, 'Sparkling Champagne Accord'],
  [/كرز أسود/g, 'Black Cherry'],
  [/فاوانيا/g, 'Peony'],
  [/بندق/g, 'Hazelnut'],
  [/لبان بخوري/g, 'Frankincense'],
  [/لبان/g, 'Frankincense'],
  [/سرو/g, 'Cypress'],
  [/بردقوش/g, 'Marjoram'],
  [/عبهر/g, 'Styrax'],
  [/سيبريول/g, 'Cypriol'],
  [/مريمية/g, 'Clary Sage'],
  [/جوزة الطيب/g, 'Nutmeg'],
  [/بيمنتو/g, 'Pimento'],
  [/سبايسي/g, 'Warm Spices'],
  [/توابل حارة/g, 'Spicy Accords'],
  [/توابل/g, 'Spices'],
  [/،/g, ','],
  [/و/g, '& ']
];

function translateNotes(arText) {
  if (!arText) return '';
  let en = arText;
  DICT.forEach(([regex, replacement]) => {
    en = en.replace(regex, replacement);
  });
  // Clean punctuation and leftover arabic
  en = en.replace(/&amp;/g, '&')
         .replace(/[\u0600-\u06FF]/g, '')
         .replace(/\s*,\s*/g, ', ')
         .replace(/\s*&\s*/g, ', ')
         .replace(/,\s*,+/g, ', ')
         .replace(/^[, ]+|[, ]+$/g, '')
         .trim();
  return en;
}

console.log('Testing translation:');
console.log(translateNotes('فراولة، تفاح، قرفة، ريحان، برتقال، وبرغموت'));
console.log(translateNotes('زنبق الوادي، يلانغ يلانغ، ورد، قهوة، وياسمين'));
